# llm/markdown_utils.py

import re

def clean_markdown_code(text):
    """
    Removes Markdown formatting and LLM commentary from generated code
    """
    # Remove triple backticks and language hints like ```java
    text = re.sub(r"```(\w+)?", "", text)

    # Remove common LLM artifacts
    text = re.sub(r"(?i)//\s*This is.*?generated by.*?\n", "", text)
    text = re.sub(r"(?i)//\s*The following class.*?\n", "", text)
    text = re.sub(r"(?i)^\s*Here's the .*?\n", "", text, flags=re.MULTILINE)

    # Remove leading/trailing whitespace
    return text.strip()
